CREATE USER LAMBDA_FUNCTION WITH PASSWORD '???' VALID UNTIL '2024-01-01';

CREATE ROLE LAMBDA;
GRANT LAMBDA TO lambda_function;

GRANT INSERT ON TABLE postgres.PUBLIC.raw_events TO LAMBDA;

SET ROLE POSTGRES;

INSERT INTO postgres.PUBLIC.raw_events (EVENT, time_stamp) VALUES ('UP', CURRENT_TIMESTAMP);

SELECT * FROM postgres.public.raw_events;
